/**
 * Central DI tokens to avoid circular imports
 */
export const TOKENS = {
  LOGGER: Symbol.for('ILogger'),
  FILE_SYSTEM: Symbol.for('IFileSystem'),
  DIRECTORY_SERVICE: Symbol.for('DirectoryService'),
  JSON_WRITER: Symbol.for('JsonWriter'),
  STREAM_WRITER: Symbol.for('StreamWriter'),
  PATH_SERVICE: Symbol.for('IPathService'),
  SANITIZER: Symbol.for('ISanitizer'),
  PATH_VALIDATOR: Symbol.for('PathValidator'),
  CONSOLE_FORMATTER: Symbol.for('ConsoleFormatter'),
  JSON_FORMATTER: Symbol.for('JsonFormatter'),
  TABLE_FORMATTER: Symbol.for('TableFormatter'),
  DIAGNOSTIC_AGGREGATOR: Symbol.for('DiagnosticAggregator'),
  CONFIG_VALIDATOR: Symbol.for('ConfigValidator'),
  ESLINT_ADAPTER: Symbol.for('EslintAdapter'),
  TYPESCRIPT_ADAPTER: Symbol.for('TypeScriptAdapter'),
  VITEST_ADAPTER: Symbol.for('VitestAdapter'),
  TYPESCRIPT_ANALYTICS: Symbol.for('TypeScriptAnalytics'),
  DIAGNOSTIC_ANALYTICS: Symbol.for('DiagnosticAnalytics'),
  REPORTING_ORCHESTRATOR: Symbol.for('ReportingOrchestrator'),
  REPORTING_FACADE: Symbol.for('ReportingFacade'),
  CONSOLE_LOGGER: Symbol.for('ConsoleLogger'),
  FILE_WRITER: Symbol.for('FileWriter'),
  FILE_CONTENT_READER: Symbol.for('FileContentReader'),
  DIAGNOSTIC_METADATA_BUILDER: Symbol.for('DiagnosticMetadataBuilder'),
  FILE_REPORT_ASSEMBLER: Symbol.for('FileReportAssembler'),
  SOURCE_CODE_ENRICHER: Symbol.for('SourceCodeEnricher'),
  STRUCTURED_REPORT_WRITER: Symbol.for('StructuredReportWriter'),
  COLLECT_DIAGNOSTICS_USE_CASE: Symbol.for('CollectDiagnosticsUseCase'),
  GENERATE_REPORT_USE_CASE: Symbol.for('GenerateReportUseCase'),
} as const;
